# Generated by Django 2.2.5 on 2020-08-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceMaster',
            fields=[
                ('inv_invoice_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('inv_vendor_name', models.CharField(max_length=145, null=True)),
                ('inv_invoice_date', models.DateField()),
                ('inv_invoice_file', models.FileField(upload_to='media/')),
                ('inv_user', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItemsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itx_item_desc', models.CharField(max_length=150)),
                ('itx_item_quantity', models.IntegerField()),
                ('itx_item_rate', models.FloatField()),
                ('itx_inv_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.InvoiceMaster')),
            ],
        ),
    ]
